apiVersion: v1
kind: Service
metadata:
  name: nextjs-service
  namespace: default
  labels:
    app: nextjs-app
spec:
  type: LoadBalancer
  selector:
    app: nextjs-app
  ports:
    - port: 80
      targetPort: 3000
      protocol: TCP
